backend:
  name: git-gateway
  branch: main
media_folder: assets/uploads
public_folder: /assets/uploads
collections:
    - name: novels
    label: 小說
    folder: _novels
    create: true
    slug: '{{slug}}'
    fields:
            - {label: 書名, name: title, widget: string}
            - {label: 作者, name: author, widget: string, default: linlinyu75}
            - {label: 封面, name: cover, widget: image, required: false}
            - {label: 簡介, name: description, widget: text, required: false}
    - name: chapters
    label: 章節
    folder: _chapters
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
            - {label: 所屬小說, name: novel, widget: relation, collection: novels, value_field: title, search_fields: [title], display_fields: [title]}
            - {label: 章節標題, name: title, widget: string}
            - {label: 序號, name: chapter_number, widget: number, value_type: int, min: 1}
            - {label: 日期, name: date, widget: datetime}
            - {label: 內容, name: body, widget: markdown}
